services:
- type: web
  name: youtube-ai-api
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn youtube_summary:app
  envVars:
  - key: GEMINI_API_KEY
    sync: false